### ISSUE TITLE
Bug CSS sur le menu avec les images

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/agd.data.gouv.fr#10]
Visible par exemple sur https://agd.data.gouv.fr/2018/04/10/rapport-2016-1017-de-ladministrateur-general-des-donnees-la-donnee-comme-infrastructure-essentielle/ au hover du menu.

![](https://puu.sh/CIaKE/1853c59760.png)

Probablement un `z-index` à configurer

**Comment by thimy** [comment]
Je pense que ça peut se corriger en mettant à jour la gem du thème, je regarde un peu plus tard.

**Comment by AntoineAugusti** [comment]
Tackled in #11
